<?php
/**
 * @file
 * Views integration for geolocation module and proximity search calculations
 */

/**
 * Add the views .inc file.
 */
module_load_include('inc', 'geolocation_proximity', 'views/geolocation_proximity.views');

/**
 * Implements hook_views_api()
 */
function geolocation_proximity_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_autoload_info().
 */
function geolocation_proximity_autoload_info() {
  return array(
    // Views handlers:
    'geolocation_proximity_views_handler_field_distance' => 'views/geolocation_proximity_views_handler_field_distance.inc',
    'geolocation_proximity_views_handler_filter_distance' => 'views/geolocation_proximity_views_handler_filter_distance.inc',
  );
}

/**
 * Calls a hook to allow modules to set the visitor's current location.
 */
function _geolocation_proximity_get_client_location() {
  $client_location = array(
    'latitude' => NULL,
    'longitude' => NULL,
  );

  // Call hook_geolocation_proximity_client_location_alter() to allow other
  // modules to alter the client location array: latitude and longitude.
  backdrop_alter('geolocation_proximity_client_location', $client_location);

  return $client_location;
}
