<?php
/**
 * @file
 * Views integration for geolocation module and proximity search calculations
 */

/**
 * Implements hook_views_api()
 */
function geolocation_proximity_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_field_views_data_alter()
 */
function geolocation_proximity_field_views_data_alter(&$result, $field, $module) {
  if ($module == 'geolocation') {
    $field_name = $field['field_name'];
    $result['field_data_' . $field_name][$field['field_name'] . '_distance'] = array(
      'group' => 'Geolocation',
      'title' => $field_name . ' - distance',
      'help' => 'Filter view results by distance, using geolocation data from <em>' . $field_name . '</em>.',
      'title short' => $field_name . ' - Distance',
      'filter' => array(
        'table' => 'field_data_' . $field_name,
        'handler' => 'geolocation_proximity_views_handler_filter_distance',
      ),
    );
  }
}

/**
 * Implements hook_views_data()
 */
function geolocation_proximity_views_data() {
  $data = array();
  foreach (field_info_fields() as $field) {
    if ($field['type'] != 'geolocation_latlng') {
      continue;
    }

    $field_name = 'field_data_' . $field['field_name'];
    $data[$field_name][$field['field_name']]['filter'] = array(
      'handler' => 'geolocation_proximity_views_handler_filter_distance',
    );
  }
  return $data;
}
